[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "ft_stem_split"
version = "0.1.0"
description = "Séparateur de sources audio from scratch (U-Net Keras, déploiement ARM/Pi 5)"
requires-python = ">=3.10"

[tool.setuptools.packages.find]
where = ["src"]

[project.scripts]
ft_stem_split = "ft_stem_split.cli.main:cli"
